### ISSUE TITLE
Error, cant activate the plugin

### ISSUE THREAD

**Issue by qaywsxedcrfvtgb** [wpexpertsio/WP-Contact-Slider#1]
Hi, when I try to activate the plugin it shows this error:

Warning: require_once(/data/web/virtuals/150483/virtual/www/domains/MYDOMAIN/wp-content/themes/MYTHEME/includes/meta-box/inc/common.php): failed to open stream: No such file or directory in /data/web/virtuals/150483/virtual/www/domains/MYDOMAIN/wp-content/plugins/wp-contact-slider/inc/meta-box/meta-box.php on line 27

Fatal error: require_once(): Failed opening required ‘/data/web/virtuals/150483/virtual/www/domains/MYDOMAIN/wp-content/themes/MYTHEME/includes/meta-box/inc/common.php’ (include_path=’.:/data/web/virtuals/150483/virtual’) in /data/web/virtuals/150483/virtual/www/domains/MYDOMAIN/wp-content/plugins/wp-contact-slider/inc/meta-box/meta-box.php on line 27

What to do?

**Comment by wpexpertsio** [comment]
This WordPress contact Slider issue was discussed over here and is resolved now.
[https://wordpress.org/support/topic/error-cant-activate-the-plugin-2/](https://wordpress.org/support/topic/error-cant-activate-the-plugin-2/)
